### ISSUE TITLE
请问有完整的项目么

### ISSUE THREAD

**Issue by huzi666** [Mrsandman327/Canon_Test#1]
在qt里始终连接不到edsdk.lib这个库，提示:-1: error: LNK1104: 无法打开文件“EDSDK/Library/EDSDK.lib”，最近也在搞佳能相机的二次开发，感觉您这个挺详细的，只是您这个都是头文件和源文件，不知道有没有项目呢，感谢~

**Comment by Mrsandman327** [comment]
这个是使用MFC开发的，没试过QT开发
